data_elements = {
    'Dataelement_10_2': 'Date of start of pharamacotherapy',
    'Dataelement_11_2': 'Date of end of pharamcotherapy',
    'Dataelement_12_4': 'Date of start of radiation therapy',
    'Dataelement_13_2': 'Date of end of radiation therapy',
    'Dataelement_14_3': 'Microsatellite instability',
    'Dataelement_15_2': 'Mismatch repair gene expression',
    'Dataelement_16_3': 'Risk situation (only HNPCC)',
    'Dataelement_20_3': 'KRAS exon 2 (codons 12 or 13)',
    'Dataelement_21_5': 'KRAS exon 3 (codons 59 or 61)',
    'Dataelement_22_4': 'KRAS exon 4 (codons 117 or 146) mutation status',
    'Dataelement_23_5': 'NRAS exon 2 (codons 12 or 13)',
    'Dataelement_24_4': 'NRAS exon 3 (codons 59 or 61)',
    'Dataelement_25_3': 'NRAS exon 4 (codons 117 or 146)',
    'Dataelement_2_2': 'Participation in clinical study',
    'Dataelement_30_3': 'MRI',
    'Dataelement_31_3': 'CT',
    'Dataelement_33_1': 'Specific response',
    'Dataelement_34_1': 'Date response was obtained in weeks since initial diagnosis',
    'Dataelement_35_3': 'Date of start of targeted therapy',
    'Dataelement_36_1': 'Date of end of targeted therapy',
    'Dataelement_3_1': 'Age at diagnosis (rounded to years)',
    'Dataelement_49_1': 'Surgery type',
    'Dataelement_4_3': 'Time of recurrence (metastasis diagnosis)',
    'Dataelement_51_3': 'Date of diagnosis',
    'Dataelement_53_3': 'WHO version',
    'Dataelement_54_2': 'Material type',
    'Dataelement_55_2': 'Preservation mode',
    'Dataelement_56_2': 'Sample ID',
    'Dataelement_57_3': 'Availability digital imaging',
    'Dataelement_58_2': 'Availability invasion front digital imaging',
    'Dataelement_59_5': 'Scheme of pharmacotherapy',
    'Dataelement_5_2': 'Vital status',
    'Dataelement_61_5': 'Liver imaging',
    'Dataelement_63_4': 'Lung imaging',
    'Dataelement_67_1': 'Other surgery type',
    'Dataelement_68_2': 'Localization of metastasis',
    'Dataelement_6_3': 'Timestamp of last update of vital status',
    'Dataelement_70_2': 'Stage',
    'Dataelement_71_1': 'Primary Tumor',
    'Dataelement_73_3': 'UICC version',
    'Dataelement_75_1': 'Distant metastasis',
    'Dataelement_77_1': 'Regional lymph nodes',
    'Dataelement_7_2': 'Overall survival status',
    'Dataelement_81_3': 'Other pharmacotherapy scheme',
    'Dataelement_82_1': 'Biological material from recurrence available',
    'Dataelement_83_1': 'Grade',
    'Dataelement_85_1': 'Biological sex',
    'Dataelement_87_1': 'BRAF, PIC3CA, HER2 mutation status',
    'Dataelement_88_1': 'Colonoscopy',
    'Dataelement_89_3': 'Year of sample collection',
    'Dataelement_8_3': 'Time difference between initial diagnosis and surgery',
    'Dataelement_91_1': 'Morphology',
    'Dataelement_92_1': 'Localization of primary tumor',
    'Dataelement_93_1': 'Location of the tumor',
    'Dataelement_9_2': 'Surgery radicality'
}
form_number={
    'sample':'1',
    'histopathology':'2',
    'pharmacotherapy':'3',
    'response to therapy':'4',
    'radiation therapy':'5',
    'targeted therapy':'6',
    'surgery':''
        }

